### PR TITLE
WIP: Comply html reporter format

### PR DESCRIPTION
**Pull request by legopiraat**
Created a mapper that will map the current run results to the json format from the mutation testing elements. 

Status:
Still very much work in progress and am still missing some of the fields. But the first setup has been made.

### CODE REVIEW

**Comment by hugo-vrijswijk** [comment]
Looks like a good start. Did you give changing the current model to more closely match the HTML reporter model a try? Though i imagine not everything in it is applicable.

@nicojs Right now we have a console-reporter. But Stryker4s only calls a single one. That would be something we'd have to change too.

**Comment by legopiraat** [comment]
Good suggestion about the HTML-reporter feature branch, will do that no problem. 

I've looked into changing the current model just for a bit and ended up in a limbo where i changed everything. I'll try to change a few small things here and their but for now i think the mapper will do the majority.

**Comment by legopiraat** [comment]
Create a branch called `HTML-Reporter` which will be the main branch for this new feature.

**Comment by hugo-vrijswijk** [comment]
Closed. We'll move the discussion into the issue #29 or Gitter. A PR can be made when code is ready to be merged

**Pull request closed without merging**
